"use strict";
exports.__esModule = true;
var persona_1 = require("./persona");
var direccion_1 = require("./direccion");
var telefono_1 = require("./telefono");
var mail_1 = require("./mail");
var direccion1 = new direccion_1.direccion("Principal ", 2, 2, "a", 36500, "Lalín", "Potevedra");
var telefono1 = new telefono_1.telefono("Oficina", 685230645);
var mail1 = new mail_1.mail("Personal", "angelhidalgo@gmail.com");
var persona1 = new persona_1.persona("Angel ", "Hidalgo", 30, "09841431F", "17-7-90", "Azul", "H", "Sin nota", direccion1, mail1, telefono1);
var direccion2 = new direccion_1.direccion("La iglesia ", 4, 3, "a", 36500, "Lalín", "Potevedra");
var telefono2 = new telefono_1.telefono("Oficina", 964253698);
var mail2 = new mail_1.mail("Personal", "stevenfajardo@gmail.com");
var persona2 = new persona_1.persona("Steven ", "Fajardo", 26, "09841408s", "6-4-95", "Azul", "H", "Sin nota", direccion2, mail2, telefono2);
var direccion3 = new direccion_1.direccion("Principal ", 2, 2, "a", 36500, "Lalín", "Potevedra");
var telefono3 = new telefono_1.telefono("Oficina", 685320645);
var mail3 = new mail_1.mail("Personal", "angelhidalgo@gmail.com");
var persona3 = new persona_1.persona("Lore ", "Olivero", 23, "09841631F", "21-11-95", "Azul", "H", "Sin nota", direccion3, mail3, telefono3);
var personas = [persona1, persona2, persona3];
console.log('personas: ', personas);
console.log("----------------------------------------");
var filterPErson = personas.filter(function (element) { return element.dni == "09841431F"; });
var person = filterPErson[0];
console.log("Modificaci\u00F3n de persona por el DNI " + person.dni + " sin modificar");
console.log(person);
person.setDirecciones(direccion2);
person.setMail(mail2);
person.setTelefono(telefono2);
console.log("Modificaci\u00F3n de persona por el DNI " + person.dni + " modificado");
console.log(person);
